### ISSUE TITLE
Code Metrics in PRs via github-actions [bot]

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#109]
Recently saw this code/build/assets size table in a PR: https://github.com/bangle-io/bangle-io/pull/417
![image](https://user-images.githubusercontent.com/194400/198988638-38855859-f865-4c3a-8211-1dd5b989296e.png)

Very keen to find out more. 🤞 

# Todo

+ [ ] ***Investigate*** if this only applies to `JS` (or if it's available in `TypeScript`, `Dart` or `Elixir`?) 🔍 
  + [ ] ***Comment*** on this issue with what you discover! 💬 
+ [ ] ***Apply*** it to one of our projects if applicable to track file size fluctuations in PRs. 👩‍💻 
+ [ ] ***Report*** back once we've seen it working in our own project(s). 📝
