### ISSUE TITLE
`Playwright`?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#135]
Seen some recent buzz online for https://github.com/microsoft/playwright as a Web App Testing Tool.
![image](https://github.com/dwyl/technology-stack/assets/194400/6420a555-4195-48f7-ab15-98b449cc81e6)

https://playwright.dev/
![image](https://github.com/dwyl/technology-stack/assets/194400/c56d6fe0-fece-41e2-8db5-c59ca39357f7)

# Todo

+ [ ] Investigate using `Playright` to test a basic Web App including
  + [ ] Visit a web app
  + [ ] Input form data
  + [ ] Capture Screenshots
  + [ ] Basic Navigation to different pages
  + [ ] Authentication? 
+ [ ] Most importantly: Does it run on `GitHub Actions`? 

If we can get this working in a basic demo app e.g. [`fields-demo`](https://github.com/dwyl/fields-demo) we could consider using it for our `MVP`, then `Auth` and `App` for testing actual features! 

> **Note**: yes, I _know_ it's [`MSFT`](https://programmerbear.com/why-microsoft-is-evil) ... 🙄 
> So we need to do some analysis to determine if `Playright` is _significantly_ faster/easier than [`Cypress`](https://github.com/cypress-io/cypress) 💭 
> Of _particular_ interest to me is `Codegen` i.e. recording a usage session an translating that to test automation code. 🧑‍💻
