### ISSUE TITLE
How do we ship a "Native" (Mobile) App into the Apple App Store / Google Play Store?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#24]
_Many_ of our (existing/potential) clients _still_ ask us for "Native" (_Mobile_) Applications. 
While we have not _pursued_ Native App projects in the past, we have _indirectly_ ended up working on them as "_special requests_" for specific clients. 

> # Let's open the `discussion` on "_Native_" (_Mobile_) Apps as a _team_ so we can capture the _sentiment_.

## Todo:

+ [ ] initial investigation (Blog Post) titled "_Do we **need** a **Native** (Mobile) App_?" 
  + [ ] What are the **costs/benefits** of having an app in the Google Play or Apple App Store ?
  + [ ] What `features` are _**only** available_ in _Native_ (Mobile) Apps vs HTML5+PWA ?
    + [ ] Notifications
    + [ ] Home-screen Icon
    + [ ] Offline-support
+ [ ]  What are the _**minimum requirements**_ to deploy a `"Hello World"` app into the app store:
  + [ ] Apple App Store
  + [ ] Google Play Store
+ [ ] Investigate our options for developing "Native" 
  + [ ] "Native Native":
    + [ ] Swift (iOS)
    + [ ] Java (Android)
  + Phonegap http://phonegap.com/ _are people still using it?_ 
     + Does Telerik make it easier? http://www.telerik.com/campaigns/platform/phonegap
     + Or Phonegap Build: https://build.phonegap.com/ (_are people using it?_)
  + React Native ... 
+ [ ] how much can be achieved using "Progressive Web App" (PWA) technologies?
+ [ ] What are the costs/benefits of using a PWA?
  + [ ] `Time-to-market` (_a PWA requires no "store" approval and can be deployed to devices in minutes not hours/days! all subsequent updates are done incrementally without having to download an entire `20mb binary`!_)
  + [ ] How does the `add-to-homescreen` prompt/button reduce friction to adoption (_by not forcing someone to go to an "App Store" and **download** a `20Mb binary` do we have a much better chance of "converting" people to returning users?_) 🏠 
+ [ ] What is the _timeline_ for `PWA` feature availability on iOS? ⌛️

**Comment by raptortech-js** [comment]
An argument for Progressive Web Apps: https://cloudfour.com/thinks/ios-doesnt-support-progressive-web-apps-so-what/
It's important to note that at the moment, there's a lot that PWAs cannot do on Safari, including particularly the ability to work offline or install to the home screen.

**Comment by sohilpandya** [comment]
I am _pro_ **swift**(native native) at this moment in time, just because I am learning to build native apps and will log the learning process here -> https://github.com/dwyl/learn-apple-watch-development/issues
In terms of the Hello world app, here is the example -> https://github.com/dwyl/learn-apple-watch-development/issues/11. Putting it in production is a whole another process that I haven't yet look at. 

PWA or native is a very good question, I feel that we need to look at it on a case by case basis and at times, it's just about teaching our clients about benefits of PWA (as most of them do not need a native app) over native. But there are certain features that are only available on native and if the client wants one of those features, is it better to just go native straight away?

**Comment by nelsonic** [comment]
https://medium.com/@addyosmani/a-tinder-progressive-web-app-performance-case-study-78919d98ece0
