### ISSUE TITLE
David-DM (Dependency Management) Offline > Alternative for Badge?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#88]
# Context

We have be using David DM for 5 + years to track our dependencies in our Node.js projects. 📈 
We _love_ the simplicity of the service and the author is a certified awesome dude! https://twitter.com/_alanshaw ❤️ 

Occasionally, the service would be interupted and the badge would display as a "broken" image:
e.g: https://github.com/dwyl/terminate
![image](https://user-images.githubusercontent.com/194400/150763816-9db37f6e-4027-41a0-be7a-0001620103a3.png)

This morning I noticed the following in one of our projects: https://github.com/dwyl/env2

![env2-deps-badge-no-longer-available](https://user-images.githubusercontent.com/194400/150763502-3e1a17a6-30d9-4c9f-a12f-6d381deb95aa.png)

![image](https://user-images.githubusercontent.com/194400/150763602-353a84df-ea03-4f64-850d-5293956705e2.png)

Running a **_FREE_ service** is a **_thankless_ task**. 😞   We know ... e.g: https://github.com/dwyl/hits/issues/117

https://david-dm.org/
![image](https://user-images.githubusercontent.com/194400/150749809-6ea0ffa5-216c-4411-a439-05a60056d3ce.png)

https://github.com/alanshaw/david/issues
![image](https://user-images.githubusercontent.com/194400/150750402-2e87b0d9-17ec-41dd-9ce7-f91bff9bc79a.png)

https://github.com/alanshaw/david/issues?q=is%3Aissue+is%3Aclosed
![image](https://user-images.githubusercontent.com/194400/150762808-9aae2fec-645d-4e7e-bc98-b3a373ca3ba5.png)

# Todo

+ [ ] Reach out to Alan to determine what his future plans are for the service
  + [ ] Offer to pay for a portion of the hosting/bandwidth bills to ensure service availability.
+ [ ] If he isn't planning on spending more effort/cash on it, consider/search for alternatives.
