### ISSUE TITLE
Tidy Up?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#91]
_Re-reading_ the `README.md` of this repo with [***`Shoshin`***](https://en.wikipedia.org/wiki/Shoshin) it feels _cluttered_ and potentially _confusing_. 🤷 
Going to spend **`T1h`** doing a tidy up. Don't know when yet. But ideally _soon_. 🔜  👨‍💻  

# Todo

+ [ ] Move Reference to the "Old" Stack to a new `old-stack.md` file to declutter this one.
+ [ ] Finish the Flutter PR: https://github.com/dwyl/technology-stack/pull/80 to close #81 
  + [ ] Link to `flutter.md` from the `README.md` and explain the context/roadmap.
+ [ ] Remove `Redis` and `ElasticSearch` from the Tech Stack diagram. 
+ [ ] Link to Radical Simplicity https://github.com/nelsonic/nelsonic.github.io/issues/842
+ [ ] Update the Tech diagram in the `README.md` 
+ [ ] Close any open [issues](https://github.com/dwyl/technology-stack/issues) that are no longer relevant (backlog grooming).

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/185086864-1e1dd075-18a8-45ff-9b51-84f9e17fe116.png)

![image](https://user-images.githubusercontent.com/194400/185088113-b40f169f-71c7-4139-b984-cf518e4bc0f4.png)

![image](https://user-images.githubusercontent.com/194400/185088279-241c2d23-3986-4820-9b59-7acb6f9b8235.png)

**Comment by nelsonic** [comment]
Busy doing my own review now and cutting out any parts that are no longer relevant or too "waffly" ... 🧇
