### ISSUE TITLE
Tailwind CSS

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technology-stack#94]
As noted by @SimonLab in https://github.com/dwyl/technology-stack/issues/74 Tailwind is _similar_ to Tachyons  😍  
However it _appears_ to have more traction, some might say it has a [tailwind](https://en.wikipedia.org/wiki/Headwind_and_tailwind) propelling it ... 🌬️ 

https://tailwindcss.com/
![image](https://user-images.githubusercontent.com/194400/172074225-2089cd71-8547-4fa5-a391-23a75d44303b.png)

My reading of the Tailwind landing page is that it doesn't offer much ***`new`*** over Tachyons, 🤷‍♂️ 
but the ***packaging*** seems far more _polished_ ... 💄 

From Chris' recent post:  https://fly.io/phoenix-files/tailwind-standalone/  [ 2021-12-22 ]
It's clear that Tailwind will be included as the **`default` CSS Framework** in **`Phoenix`** quite soon: 🔜 
![image](https://user-images.githubusercontent.com/194400/172074986-dad938a6-c96c-43ad-b238-c9eced2a84ce.png)

https://github.com/phoenixframework/tailwind

Since [**`v1.4`**](https://github.com/phoenixframework/phoenix/commit/463e9d282e999fff1737cc6ca09074cf3dbca4ff) all Phoenix Apps include the Milligram CSS Framework https://milligram.io 
e.g:  [`assets/css/phoenix.css`](https://github.com/dwyl/auth/blob/568d0fd7a4a4f7ec53514c76e0e263c3f82e61ca/assets/css/phoenix.css) 
all of our **`v1.6.x`** Apps have it ... and it's been a _pain_ to override with Tachyons! 🙄 

It appears as though Milligram hasn't been updated in a ***`while`*** ...  https://github.com/milligram/milligram
![image](https://user-images.githubusercontent.com/194400/172075754-583b6491-2fa9-4107-8915-a0b2a6ac14b2.png)

Pull Requests ignored: https://github.com/milligram/milligram/pulls
![image](https://user-images.githubusercontent.com/194400/172076352-301130eb-a703-4e47-9ea4-f7eb21db83be.png)

The creator of Milligram appears to be taking a break from GitHub: https://github.com/cjpatoilo
![image](https://user-images.githubusercontent.com/194400/172076419-8c742023-5818-479d-bce4-193f6a2b2861.png)

Makes perfect sense. There's (a _lot_) more to life than GitHub/Code. ☀️ 

Anyway, back to Tailwind. 
The writing is on the wall: **`Phoenix`** will include it (_prob **`v.1.7+`**_) so we should consider adopting it. 💭 

# Overview

https://tailwindcss.com/docs/utility-first
![image](https://user-images.githubusercontent.com/194400/172078735-77535ae5-ecac-4623-a34a-a8033048cb26.png)

### Context

https://podcast.thinkingelixir.com/21
![image](https://user-images.githubusercontent.com/194400/172071830-b4741c12-c814-4ebb-9624-03e45d07ec28.png)

https://changelog.com/jsparty/155 
![image](https://user-images.githubusercontent.com/194400/172070609-01af44d8-2a08-44dd-a7b3-877dc1aa4d9d.png)
> **Note**: skip the first 4 mins of "sponsors" and intros to the actual interview. Play at 1.5x Speed. 

Tailwind UI looks good but has restrictive license: https://tailwindui.com/license
> "_In simple terms, use Tailwind UI for anything you like as long as it doesn't compete with Tailwind UI._"

> "_Creating an admin panel tool (like [Laravel Nova](https://nova.laravel.com/) or [ActiveAdmin](https://activeadmin.info/)) that is made available either for sale or for free_"

DaisyUI appears to be a viable [MIT license](https://github.com/saadeghi/daisyui/blob/master/LICENSE) alternative: https://github.com/saadeghi/daisyui

# Todo

+ [x] Read the docs and see how it differs / improves upon the utility class model in Tachyons. 
(_is it just packaging/presentation or something genuinely different/better...?_)
+ [x] Try it in a sample project e.g. one of the recent Demo apps: https://github.com/dwyl/gitea-demo/issues/12
 > See: https://pragmaticstudio.com/tutorials/adding-tailwind-css-to-phoenix
+ [x] Evaluate if the Hype is justified and we should just learn+use it!

**Comment by nelsonic** [comment]
Going to track our learning in: https://github.com/dwyl/learn-tailwind

**Comment by nelsonic** [comment]
Official instructions: https://tailwindcss.com/docs/guides/phoenix

**Comment by nelsonic** [comment]
Just reading through https://tailwindcss.com/docs/customizing-colors ...
While I'm not a fan of _needing_ to have JS to "process" the CSS file,
I can certainly see the _power_ of this approach.
And with **`esbuild`** handing the build + live reload it's a reasonable workflow. 💭

**Comment by nelsonic** [comment]
Intro logo:
![tailwind-css-logo](https://user-images.githubusercontent.com/194400/174442927-3476e0a5-eca7-43fd-b68c-5a3f3248e1f8.svg)

**Comment by nelsonic** [comment]
![tailwind-play-color-change](https://user-images.githubusercontent.com/194400/174629457-cda42165-8242-4f04-afe1-8d7c75da6c2b.gif)

**Comment by nelsonic** [comment]
**FYI**: I'm deep-diving into _understanding_ how the internals of `Tailwind` work
and how _we_ can use it for our project(s)
so that I grok it well enough to write a _tutorial_ that will be useful to _other_ people.

I know I'm _definitely_ doing more work on this _up-front_ than I strictly _need_ to. ⏳ 
But as with all our other tutorials, examples & demos, I know that:

**a)** it will be **_immediately_ beneficial to `me`** to have a good understanding.
**b)** we will point **new-joiners** to the doc and encourage them to ***extend/update*** it as part of their learning
**c)** making it **_generally_ useful to _anyone_** means we make something that other people can _contribute_ to. That makes everyones' lives better. 
**d)** I will ***refer back*** to it in the future when I need a refresher. 

Going to try and wrap up my "first pass" on this today and hand-over to @SimonLab for review+improvements. 🤞

**Comment by nelsonic** [comment]
https://www.tailwindtoolbox.com/  
![tailwindtoolbox](https://user-images.githubusercontent.com/194400/174825181-04c74957-4f69-4c9f-9290-d297051eeee5.png)

**Comment by nelsonic** [comment]
![admin-dashboard-example](https://user-images.githubusercontent.com/194400/174831515-304859e9-416a-4af2-8268-2c1900b62891.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/174838767-20bf201e-3179-4ff9-8d5d-751295d1d069.png)

**Comment by nelsonic** [comment]
https://github.com/dwyl/learn-tailwind already in decent state. 😜

**Comment by nelsonic** [comment]
Included in #80 as part of updating the core stack to `PETAL` #87
